# Generated by Django 4.2.3 on 2023-07-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0003_alter_walletuser_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletuser',
            name='wallet_address',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
