# Generated by Django 4.2.3 on 2023-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0004_alter_walletuser_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='hashed_wallet_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
