# Generated by Django 4.2.3 on 2023-07-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0005_walletuser_hashed_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletuser',
            name='hashed_wallet_address',
        ),
    ]
