# Generated by Django 4.2.3 on 2023-07-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0006_remove_walletuser_hashed_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translator_app.walletuser')),
            ],
        ),
    ]
