# Generated by Django 4.2.3 on 2023-07-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0007_usernft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNFT',
        ),
    ]
